//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SStimStat.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class f_alpha_0_025
    {
        public short denom_df { get; set; }
        public Nullable<float> ndf_1 { get; set; }
        public Nullable<float> ndf_2 { get; set; }
        public Nullable<float> ndf_3 { get; set; }
        public Nullable<float> ndf_4 { get; set; }
        public Nullable<float> ndf_5 { get; set; }
        public Nullable<float> ndf_6 { get; set; }
        public Nullable<float> ndf_7 { get; set; }
        public Nullable<float> ndf_8 { get; set; }
        public Nullable<float> ndf_9 { get; set; }
        public Nullable<float> ndf_10 { get; set; }
        public Nullable<float> ndf_12 { get; set; }
        public Nullable<float> ndf_15 { get; set; }
        public Nullable<float> ndf_20 { get; set; }
        public Nullable<float> ndf_24 { get; set; }
        public Nullable<float> ndf_30 { get; set; }
        public Nullable<float> ndf_40 { get; set; }
        public Nullable<float> ndf_60 { get; set; }
        public Nullable<float> ndf_120 { get; set; }
    }
}
