//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SStimStat.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class raysstim_statsEntities : DbContext
    {
        public raysstim_statsEntities()
            : base("name=raysstim_statsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<f_alpha_0_025> f_alpha_0_025 { get; set; }
        public virtual DbSet<f_alpha_0_05> f_alpha_0_05 { get; set; }
        public virtual DbSet<user_profile> user_profile { get; set; }
        public virtual DbSet<t_distribution> t_distribution { get; set; }
        public virtual DbSet<z_distribution> z_distribution { get; set; }
    }
}
