//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SStimStat.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_distribution
    {
        public int df { get; set; }
        public Nullable<float> c_0_25 { get; set; }
        public Nullable<float> c_0_1 { get; set; }
        public Nullable<float> c_0_05 { get; set; }
        public Nullable<float> c_0_025 { get; set; }
        public Nullable<float> c_0_01 { get; set; }
        public Nullable<float> c_0_005 { get; set; }
    }
}
