//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SStimStat.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class z_distribution
    {
        public short id { get; set; }
        public Nullable<float> Z { get; set; }
        public Nullable<float> c_0 { get; set; }
        public Nullable<float> c_0_01 { get; set; }
        public Nullable<float> c_0_02 { get; set; }
        public Nullable<float> c_0_03 { get; set; }
        public Nullable<float> c_0_04 { get; set; }
        public Nullable<float> c_0_05 { get; set; }
        public Nullable<float> c_0_06 { get; set; }
        public Nullable<float> c_0_07 { get; set; }
        public Nullable<float> c_0_08 { get; set; }
        public Nullable<float> c_0_09 { get; set; }
    }
}
